### ISSUE TITLE
Missing solar2d audio api `audio.getSourceFromChannel`.

### ISSUE THREAD

**Issue by zero-meta** [siudesu/SoLoudModule#5]
Hi!
I use this code to control sound speed:
```lua
local speed = 0.5
local source = audio.getSourceFromChannel(channel)
al.Source(source, al.PITCH, speed)
```
Is there something similar api in `plugin.soloud`?

**Comment by siudesu** [comment]
I have totally forgotten about those undocumented functions. 

SoLoud has:
`soloud.setRelativePlaySpeed(audioSourceID, pitch)`

With the plugin, you can do the following in the module, inside M.play(), you can test by adding this line:
`soloudCore:setRelativePlaySpeed(channelData.handleID, 0.5)`

I have yet to go over all of SoLoud's features and implement them.

**Comment by zero-meta** [comment]
Thanks! I will try to test it.

**Comment by siudesu** [comment]
This is [now implemented](https://github.com/siudesu/SoLoudModule/commit/22c19c5598daf8b2b9f9329807caae6e7e5a57d8).

You now have new functions that can provide you same effect: 
`M.setPitch(channel, pitchValue)`
`M.setSpeed(channel, speedValue)`

You can also set it during M.play():
```lua
local BGM = AUDIO.loadStream("CoolMusic.mp3")
AUDIO.play(BGM , {pitch=0.5, channel=1})
```
